# Generated by Django 5.0.4 on 2024-04-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetGuru', '0002_appuser_private_key_alter_appuser_email_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='private_key',
            field=models.CharField(max_length=100),
        ),
    ]
